### ISSUE TITLE
rename organization

### ISSUE THREAD

**Issue by jaredj** [msimerson/log-ship-elastic-postfix#25]
Let's rename this organization so it is no longer associated with EOL'd email security products :)  @msimerson any ideas?  Most of the active repos in here have to do with parsing logs and/or sending them to ES.

**Comment by msimerson** [comment]
I'm trying to think of a reason leaving them in the org has value. Another option would be to transfer the repos that have a maintainer count=1 into the developer account of the maintainer.

**Comment by jaredj** [comment]
If I'm not mistaken that is the case for every repo in this org, although I'm not sure of the best way to accomplish that transfer with minimal disruption to contributors

**Comment by msimerson** [comment]
Hrmm, maybe maintain the old URLs by:
1. transfer to maintainer account
2. fork the repo into this org

That way, the GitHub interface shows where the new canonical master is, and links all still work.
Thoughts?

**Comment by jaredj** [comment]
Sounds like a plan.  Maybe after doing the first step we can check in case Github has some magic to make the second step unnecessary

**Comment by jaredj** [comment]
I just tested with a repository I was going to delete anyway, and after transferring the repo to jaredj, https://github.com/doublecheck/board redirects to https://github.com/jaredj/board -- so it seems as though the transfer alone is good enough :)

**Comment by msimerson** [comment]
> so it seems as though the transfer alone is good enough

I think that after some period of time the redirects expire. That's what my experience has been in the past.

**Comment by jaredj** [comment]
ah, then your plan sounds good :)
